#!/bin/bash
set -e

# Anvil fork uses chainId 31337
BROADCAST_DIR="packages/contracts/broadcast/DeployLocal.s.sol/31337"
FRONTEND_CONFIG="packages/frontend/src/config/contracts.generated.ts"

if [ ! -f "$BROADCAST_DIR/run-latest.json" ]; then
  echo "No broadcast file found at $BROADCAST_DIR/run-latest.json"
  echo "Run 'forge script script/DeployLocal.s.sol --broadcast' first."
  exit 1
fi

# Parse contract addresses from broadcast output (filter CREATE transactions only)
ESCROW_VAULT=$(jq -r '[.transactions[] | select(.contractName=="EscrowVault" and .transactionType=="CREATE")] | .[0].contractAddress' "$BROADCAST_DIR/run-latest.json")
INSURANCE_POOL=$(jq -r '[.transactions[] | select(.contractName=="InsurancePool" and .transactionType=="CREATE")] | .[0].contractAddress' "$BROADCAST_DIR/run-latest.json")
TRIGGER_ORACLE=$(jq -r '[.transactions[] | select(.contractName=="TriggerOracle" and .transactionType=="CREATE")] | .[0].contractAddress' "$BROADCAST_DIR/run-latest.json")
REPUTATION_ENGINE=$(jq -r '[.transactions[] | select(.contractName=="ReputationEngine" and .transactionType=="CREATE")] | .[0].contractAddress' "$BROADCAST_DIR/run-latest.json")
BASTION_ROUTER=$(jq -r '[.transactions[] | select(.contractName=="BastionRouter" and .transactionType=="CREATE")] | .[0].contractAddress' "$BROADCAST_DIR/run-latest.json")
TEST_TOKEN=$(jq -r '[.transactions[] | select(.contractName=="TestToken" and .transactionType=="CREATE")] | .[0].contractAddress' "$BROADCAST_DIR/run-latest.json")

# BastionHook is deployed via CREATE2 through BastionDeployer, not directly
# It shows up as a CREATE2 transaction from the factory
# We can find it from the deploy() call on BastionDeployer
BASTION_HOOK=$(jq -r '[.transactions[] | select(.function=="deploy(bytes32,bytes)")] | .[0].additionalContracts[0].address // empty' "$BROADCAST_DIR/run-latest.json")

# Fallback: try to find BastionHook from contractName
if [ -z "$BASTION_HOOK" ] || [ "$BASTION_HOOK" = "null" ]; then
  BASTION_HOOK=$(jq -r '.transactions[] | select(.contractName=="BastionHook") | .contractAddress // empty' "$BROADCAST_DIR/run-latest.json")
fi

# Base mainnet PoolManager (exists on fork)
POOL_MANAGER="0x498581fF718922c3f8e6A244956aF099B2652b2b"

# Compute pool ID: keccak256(abi.encode(token0, token1, fee, tickSpacing, hook))
# token0 = ETH (address(0)), token1 = TestToken, fee = 3000, tickSpacing = 60, hook = BastionHook
POOL_ID=$(cast keccak "$(cast abi-encode 'x(address,address,uint24,int24,address)' 0x0000000000000000000000000000000000000000 "${TEST_TOKEN}" 3000 60 "${BASTION_HOOK}")" 2>/dev/null || echo "")

# Get deployer address (Anvil account #0)
DEPLOYER="0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"

cat > "$FRONTEND_CONFIG" << EOF
// AUTO-GENERATED by scripts/generate-frontend-config.sh
// Base mainnet fork on Anvil (chainId 31337)
// Do not edit manually — run 'pnpm redeploy' to regenerate.

export const LOCAL_CONTRACTS = {
  31337: {
    PoolManager: "${POOL_MANAGER}",
    BastionHook: "${BASTION_HOOK}",
    EscrowVault: "${ESCROW_VAULT}",
    InsurancePool: "${INSURANCE_POOL}",
    TriggerOracle: "${TRIGGER_ORACLE}",
    ReputationEngine: "${REPUTATION_ENGINE}",
    BastionRouter: "${BASTION_ROUTER}",
    TestToken: "${TEST_TOKEN}",
  },
} as const;

export const LOCAL_POOL = {
  id: "${POOL_ID}",
  token0: "0x0000000000000000000000000000000000000000",
  token1: "${TEST_TOKEN}",
  hook: "${BASTION_HOOK}",
  isBastion: true,
  issuedToken: "${TEST_TOKEN}",
  issuer: "${DEPLOYER}",
  fee: 3000,
  tickSpacing: 60,
} as const;
EOF

echo "Frontend config generated: $FRONTEND_CONFIG"
echo "  PoolManager:      $POOL_MANAGER"
echo "  BastionHook:      $BASTION_HOOK"
echo "  EscrowVault:      $ESCROW_VAULT"
echo "  InsurancePool:    $INSURANCE_POOL"
echo "  TriggerOracle:    $TRIGGER_ORACLE"
echo "  ReputationEngine: $REPUTATION_ENGINE"
echo "  BastionRouter:    $BASTION_ROUTER"
echo "  TestToken:        $TEST_TOKEN"
