// AUTO-GENERATED by scripts/generate-frontend-config.sh
// Base mainnet fork on Anvil (chainId 31337)
// Do not edit manually — run 'pnpm redeploy' to regenerate.

export const LOCAL_CONTRACTS = {
  31337: {
    PoolManager: "0x498581fF718922c3f8e6A244956aF099B2652b2b",
    BastionHook: "0xe2af675ee9f360aa351427556849e65ab4d7cac8",
    EscrowVault: "0xc334c5d0fc7fb1c5349d4f5602a0862aafdd82ec",
    InsurancePool: "0x68b518788565c6542eda1e012d76f0117bfc094c",
    TriggerOracle: "0xdbc6d5ebde01187bbd091dc0afa20c3ac2ffa907",
    ReputationEngine: "0x81dd803f1ad0b85ba011ec0552a04ef5391f59bb",
    BastionSwapRouter: "0x88e7452883a777801990c6916ffa0bc647cbef9b",
    BastionPositionRouter: "0x414737ec6c8cbde63e129e0e7bb6846d6c0f7f17",
    TestToken: "0xdee4840bbcfbc79645575616e3be41cf9807b86a",
    AlphaToken: "0x8474bcb54f01c4beced8dc7bd88dd7fb4cdb032b",
  },
} as const;

export const LOCAL_POOL = {
  id: "0x1dc9ad7d427ce7a611ae11ec1697c665f224b688d9ab98b406388c7d09dc27fb",
  token0: "0x0000000000000000000000000000000000000000",
  token1: "0xdee4840bbcfbc79645575616e3be41cf9807b86a",
  hook: "0xe2af675ee9f360aa351427556849e65ab4d7cac8",
  isBastion: true,
  issuedToken: "0xdee4840bbcfbc79645575616e3be41cf9807b86a",
  issuer: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266",
  fee: 3000,
  tickSpacing: 60,
} as const;
